name: doctor_pet
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.18.1
  responsive_framework: ^1.4.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/background.jpg
